import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// import dynamic from 'next/dynamic'
import { lazy } from "react";
// import Footer from "";
const Header = lazy(() => import('@/components/Header/Header'));
const MobileHeader = lazy(() => import('@/components/Header/MobileHeader'));
const Footer = lazy(() => import('@/components/Footer/Footer'));


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <MobileHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
